/**
 * Orient phase screen for commit #84.
 * 
 * Shows a 30-second audio example demonstrating the session's target technique
 * in context, generated by Lyria 3 Clip via the Gemini API.
 */

import { Audio } from 'expo-av'
import { useRouter } from 'expo-router'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Pressable, Text, View } from 'react-native'

import { SessionStepScreen } from '@/components/SessionStepScreen'
import { globalAudioManager } from '@/src/audio/GlobalAudioManager'
import { sessionHref } from '@/src/constants/sessionFlow'
import { useLessonStore } from '@/src/stores/lessonStore'

export default function OrientScreen() {
  const router = useRouter()
  const lesson = useLessonStore((s) => s.lesson)
  
  const [orientClipUrl, setOrientClipUrl] = useState<string | null>(null)
  const [annotation, setAnnotation] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [audioError, setAudioError] = useState<string | null>(null)
  const [isPlaying, setIsPlaying] = useState(false)
  const soundRef = useRef<Audio.Sound | null>(null)
  const soundInstanceId = useRef(`orient-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`)

  const togglePlayback = useCallback(async () => {
    if (!orientClipUrl) return
    setAudioError(null)

    try {
      if (isPlaying) {
        // Pause
        const sound = soundRef.current
        if (sound) {
          await sound.pauseAsync()
          setIsPlaying(false)
        }
      } else {
        // Play
        await globalAudioManager.resetToPlaybackMode()
        if (soundRef.current) {
          await soundRef.current.playAsync()
          setIsPlaying(true)
        } else {
          const { sound } = await Audio.Sound.createAsync(
            { uri: orientClipUrl },
            { shouldPlay: true }
          )
          soundRef.current = sound
          setIsPlaying(true)
          
          // Register sound with GlobalAudioManager
          globalAudioManager.registerInstance(
            soundInstanceId.current,
            'expo-sound',
            sound,
            async () => {
              if (soundRef.current) {
                await soundRef.current.unloadAsync().catch(() => {})
                soundRef.current = null
              }
            },
          )
          
          sound.setOnPlaybackStatusUpdate((status) => {
            if (status.isLoaded && status.didJustFinish) {
              setIsPlaying(false)
            }
          })
        }
      }
    } catch (e) {
      console.error('Audio playback error:', e)
      setAudioError('Could not play audio. Please try again.')
    }
  }, [orientClipUrl, isPlaying])

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (soundRef.current) {
        soundRef.current.unloadAsync()
      }
      void globalAudioManager.unregisterInstance(soundInstanceId.current)
    }
  }, [])

  useEffect(() => {
    const fetchOrientClip = async () => {
      if (!lesson?.job_id) return

      setIsLoading(true)
      setError(null)

      try {
        // Call the backend endpoint to generate the orient clip
        const response = await fetch(`${process.env.EXPO_PUBLIC_API_URL}/session/orient-clip`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            job_id: lesson.job_id,
            style_label: lesson.style_label,
            technique: null, // Would be derived from lesson content in production
            key: lesson.key,
            bpm: lesson.tempo,
          }),
        })

        if (!response.ok) {
          throw new Error(`Failed to fetch orient clip: ${response.statusText}`)
        }

        const data = await response.json()
        setOrientClipUrl(data.wav_path)
        setAnnotation(data.annotation)
      } catch (e) {
        console.error('Failed to fetch orient clip:', e)
        setError(e instanceof Error ? e.message : 'Failed to load orient clip')
      } finally {
        setIsLoading(false)
      }
    }

    void fetchOrientClip()
  }, [lesson?.job_id, lesson?.style_label, lesson?.key, lesson?.tempo])

  return (
    <SessionStepScreen
      title="Orient"
      subtitle="Listen to the target technique in context"
      showBack
      onBack={() => router.back()}
      showNext
      nextLabel="Next: Study"
      onNext={() => router.push(sessionHref('study'))}
    >
      <View className="flex-1 items-center justify-center p-4">
        {isLoading && (
          <View className="items-center">
            <Text className="font-sans text-wood-900">Generating orient clip...</Text>
          </View>
        )}

        {error && (
          <View className="items-center">
            <Text className="font-sans text-red-600">{error}</Text>
          </View>
        )}

        {audioError && (
          <View className="items-center mt-2">
            <Text className="font-sans text-red-600">{audioError}</Text>
          </View>
        )}

        {!isLoading && !error && orientClipUrl && (
          <View className="w-full gap-4">
            <View className="rounded-lg border border-wood-600/30 bg-cream-dark/30 p-4">
              <Text className="mb-2 font-sans-semibold text-wood-900">
                Orient Clip
              </Text>
              <Text className="mb-4 font-sans text-sm text-wood-900">
                {annotation}
              </Text>
              {/* Audio player */}
              <Pressable
                onPress={() => void togglePlayback()}
                className="h-16 rounded-lg border border-wood-600/50 bg-ivory items-center justify-center"
                accessibilityRole="button"
                accessibilityLabel={isPlaying ? 'Pause orient clip' : 'Play orient clip'}
              >
                <Text className="font-sans-medium text-wood-900">
                  {isPlaying ? 'Pause' : 'Play Orient Clip'}
                </Text>
              </Pressable>
            </View>
          </View>
        )}
      </View>
    </SessionStepScreen>
  )
}
