/**
 * Orient phase screen for commit #84.
 * 
 * Shows a 30-second audio example demonstrating the session's target technique
 * in context, generated by Lyria 3 Clip via the Gemini API.
 */

import { useEffect, useState } from 'react'
import { useRouter } from 'expo-router'
import { Text, View } from 'react-native'

import { SessionStepScreen } from '@/components/SessionStepScreen'
import { useLessonStore } from '@/src/stores/lessonStore'
import { sessionHref } from '@/src/constants/sessionFlow'

export default function OrientScreen() {
  const router = useRouter()
  const lesson = useLessonStore((s) => s.lesson)
  
  const [orientClipUrl, setOrientClipUrl] = useState<string | null>(null)
  const [annotation, setAnnotation] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const fetchOrientClip = async () => {
      if (!lesson?.job_id) return

      setIsLoading(true)
      setError(null)

      try {
        // Call the backend endpoint to generate the orient clip
        const response = await fetch(`${process.env.EXPO_PUBLIC_API_BASE_URL}/session/orient-clip`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            job_id: lesson.job_id,
            style_label: lesson.style_label,
            technique: null, // Would be derived from lesson content in production
            key: lesson.key,
            bpm: lesson.tempo,
          }),
        })

        if (!response.ok) {
          throw new Error(`Failed to fetch orient clip: ${response.statusText}`)
        }

        const data = await response.json()
        setOrientClipUrl(data.wav_path)
        setAnnotation(data.annotation)
      } catch (e) {
        console.error('Failed to fetch orient clip:', e)
        setError(e instanceof Error ? e.message : 'Failed to load orient clip')
      } finally {
        setIsLoading(false)
      }
    }

    void fetchOrientClip()
  }, [lesson?.job_id, lesson?.style_label, lesson?.key, lesson?.tempo])

  return (
    <SessionStepScreen
      title="Orient"
      subtitle="Listen to the target technique in context"
      showBack
      onBack={() => router.back()}
      showNext
      nextLabel="Next: Study"
      onNext={() => router.push(sessionHref('study'))}
    >
      <View className="flex-1 items-center justify-center p-4">
        {isLoading && (
          <View className="items-center">
            <Text className="font-sans text-wood-900">Generating orient clip...</Text>
          </View>
        )}

        {error && (
          <View className="items-center">
            <Text className="font-sans text-red-600">{error}</Text>
          </View>
        )}

        {!isLoading && !error && orientClipUrl && (
          <View className="w-full gap-4">
            <View className="rounded-lg border border-wood-600/30 bg-cream-dark/30 p-4">
              <Text className="mb-2 font-sans-semibold text-wood-900">
                Orient Clip
              </Text>
              <Text className="mb-4 font-sans text-sm text-wood-900">
                {annotation}
              </Text>
              {/* Audio player would go here - placeholder for now */}
              <View className="h-16 rounded bg-wood-600/20 items-center justify-center">
                <Text className="font-sans text-xs text-muted-brown">
                  Audio Player (placeholder)
                </Text>
              </View>
            </View>
          </View>
        )}
      </View>
    </SessionStepScreen>
  )
}
